### ISSUE TITLE
[WebSocket] WebSocket connection failed

### ISSUE THREAD

**Issue by Rubix982** [convergencelabs/model-getting-started#2]
Hello!

I was trying out Convergence's quick start, but I have failed to get a working example.

My steps have been has the following,

1. Get the `docker` image for Convergence as per the guide. The command ran was,

```bash
docker run -p "8000:80" --name convergence convergencelabs/convergence-omnibus
```

For the above, the logs were given as,

```text
❯ docker run -p "8000:80" --name convergence convergencelabs/convergence-omnibus
Convergence Omnibus Container
HTTP Endpoint on port: 80
2021-09-26 05:00:28,871 INFO supervisord started with pid 1
2021-09-26 05:00:28,871 INFO supervisord started with pid 1
2021-09-26 05:00:29,876 INFO spawned: 'proxy' with pid 8
2021-09-26 05:00:29,876 INFO spawned: 'proxy' with pid 8
2021-09-26 05:00:29,880 INFO spawned: 'orientdb' with pid 9
2021-09-26 05:00:29,880 INFO spawned: 'orientdb' with pid 9
2021-09-26 05:00:29,882 INFO spawned: 'convergence' with pid 10
2021-09-26 05:00:29,882 INFO spawned: 'convergence' with pid 10
           .                                          
          .`        `                                 
          ,      `:.                                  
         `,`    ,:`                                   
         .,.   :,,                                    
         .,,  ,,,                                     
    .    .,.:::::  ````                                 :::::::::     :::::::::   
    ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::  
    `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     ::: 
     ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     ::: 
      ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::  
       ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::     
        :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::   
  `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     ::: 
  `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     ::: 
    .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     ::: 
      ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     ::: 
           ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::  
           ,,:` `,,.                                  
          ,,,    .,`                                  
         ,,.     `,                                              VELOCE  
       ``        `.                                                          
                 ``                                       www.orientdb.com
                 `                                    
Warning: Nashorn engine is planned to be removed from a future JDK release

2021-09-26 05:00:30:507 INFO  Detected limit of amount of simultaneously open files is 1048576,  limit of open files for disk cache will be set to 523776 [ONative]
2021-09-26 05:00:30:517 INFO  Loading configuration from: /orientdb/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/orientdb/lib/jaxb-impl-2.3.0.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
05:00:31 INFO  ConvergenceServer$ - Using config file: /convergence-server/bin/../conf/convergence-server.conf
2021-09-26 05:00:31,024 INFO success: proxy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-09-26 05:00:31,024 INFO success: proxy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-09-26 05:00:31,024 INFO success: orientdb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-09-26 05:00:31,024 INFO success: orientdb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-09-26 05:00:31,024 INFO success: convergence entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-09-26 05:00:31,024 INFO success: convergence entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
05:00:33 INFO  ConvergenceServerActor - Convergence Server (1.0.0-rc.12) starting up...
05:00:33 INFO  ConvergenceServerActor - Convergence Server Roles: [backend, realtimeApi, restApi]
05:00:33 INFO  ConvergenceServerActor - Role 'backend' detected, activating Backend Services...
05:00:33 INFO  ConvergenceServerActor - Ensuring convergence database is initialized
05:00:33 INFO  ConvergenceServerActor - Role 'restApi' detected, activating REST API...
05:00:34 INFO  ConvergenceServerActor - Role 'realtimeApi' detected, activating the Realtime API...
05:00:34 INFO  ConvergenceRestApi - Rest API started at: http://0.0.0.0:8081
05:00:34 INFO  ConvergenceRealtimeApi - Realtime API started at: http://0.0.0.0:8080
05:00:34 INFO  ConvergenceDatabaseInitializer - Attempting to connect to the database at uri: remote:localhost:2424
05:00:34 WARN  SystemErr - Sep 26, 2021 5:00:34 AM com.orientechnologies.common.log.OLogManager log
INFO: Detected limit of amount of simultaneously open files is 1048576,  limit of open files for disk cache will be set to 523776

05:00:34 INFO  ConvergenceDatabaseInitializer - Connected to database with Server Admin
05:00:34 INFO  ConvergenceDatabaseInitializer - Convergence database auto-install is enabled, checking if the Convergence database exists
05:00:34 INFO  ConvergenceDatabaseInitializer - Convergence database does not exists, initializing it...
05:00:35 INFO  ConvergenceDatabaseInitializer - Connected to convergence database
05:00:35 INFO  ConvergenceDatabaseInitializer - Installing the Convergence database schema
05:00:40 INFO  ConvergenceDatabaseInitializer - Convergence database schema installation complete
05:00:40 INFO  ConvergenceDatabaseInitializer - Bootstrapping namespace 'convergence'
05:00:40 INFO  ConvergenceDatabaseInitializer - Bootstrapping domain 'convergence/default'
05:00:52 INFO  ConvergenceDatabaseInitializer - Bootstrapped domain 'convergence/default'
05:00:52 INFO  BackendServices - Convergence Backend Services starting up...
05:00:52 INFO  BackendServices - Convergence Backend Services started up.
```

To again confirm the status, I ran,

```bash
❯ docker ps -a
CONTAINER ID   IMAGE                                 COMMAND       CREATED          STATUS          PORTS                                   NAMES
cd38f697155a   convergencelabs/convergence-omnibus   "./boot.sh"   30 minutes ago   Up 30 minutes   0.0.0.0:8000->80/tcp, :::8000->80/tcp   convergence
```

Thus, the container is up and running. Running bash into the container works as expected with the expected files.

2. I then ran the `git` command to get the example on my machine,

```bash
git clone https://github.com/convergencelabs/model-getting-started.git
```

3. The `DOMAIN_URL` was the one as expected, and renamed `config.example.js` to `config.js`.

4. I opened the `index.html` in my browser, and another in a new tab. I did not get the realtime results, and this was in the console. 

![image](https://user-images.githubusercontent.com/41635766/134795001-4be0b5c8-8814-4884-8576-b0288dd97f1f.png)

After poking around with `console.log` in `example.js`, the culprit seems to be `Convergence.connectAnonymously(DOMAIN_URL)`.

5. To confirm the above assumptions, I visit `http://localhost:8000/console/domain/convergence/default/models/getting-started` where I see an empty `Models`, `Collection`, and `Sessions` page. For me, the dashboard looks like this,

![image](https://user-images.githubusercontent.com/41635766/134795042-85042eb1-b4b0-4230-b17a-ff27e48da4cd.png)

The connection URL is the one I have that `DOMAIN_URL` was set to, so the `DOMAIN_URL` is not at fault here.

Stack trace of the failed WS connection is,

```log
convergence.global.js:8634 WebSocket connection to 'ws://localhost:8000/api/realtime/convergence/default' failed: 
Te @ convergence.global.js:8634
open @ convergence.global.js:8657
connect @ convergence.global.js:9411
Ht @ convergence.global.js:10040
It @ convergence.global.js:10036
Jt @ convergence.global.js:10023
$t @ convergence.global.js:10012
connectAnonymously @ convergence.global.js:9996
connectAnonymously @ convergence.global.js:23093
connectAnonymously @ convergence.global.js:23224
(anonymous) @ example.js:2
```

This can be tagged `help-wanted`.

Thanks!

**Comment by Rubix982** [comment]
I don't think I've fixed this, but Chrome is acting not as expected. The above example works perfectly fine in Firefox, and the Convergence Console gets the user sessions right.

This seems to be a browser specific issue.

**Comment by Rubix982** [comment]
Some updates.


- Convergence has a problem currently with Chromium based browsers. I get failed connections with Opera, Chromium, Brave, Google Chrome, but works with Non Chromium based browsers
- A more detailed exception thanks to "Chromium", and Chromium gives a better stack trace, but I'm still unsure of the issues.

<div role="treeitem" aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(48, 57, 66); font-family: &quot;dejavu sans mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color)  !important;">WebSocket connection to 'ws:<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">//localhost:8000</span>/api/realtime/convergence/default' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(48, 57, 66); font-family: &quot;dejavu sans mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: dejavu sans mono, monospace; --source-code-font-size: 11px; --source-code-font-family: dejavu sans mono, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | Te | @ | convergence.global.js:8634
-- | -- | -- | --
  | open | @ | convergence.global.js:8657
  | connect | @ | convergence.global.js:9411
  | Ht | @ | convergence.global.js:10040
  | It | @ | convergence.global.js:10036
  | Jt | @ | convergence.global.js:10023
  | $t | @ | convergence.global.js:10012
  | connectAnonymously | @ | convergence.global.js:9996
  | connectAnonymously | @ | convergence.global.js:23093
  | connectAnonymously | @ | convergence.global.js:23224
  | (anonymous) | @ | example.js:4

</span></div>

**Comment by Rubix982** [comment]
example.js,

```javascript
// 1. Connect to the domain anonymously.
Convergence.connectAnonymously(DOMAIN_URL)
  .then(initApp)
  .catch((error) => {
    console.log("Could not connect: " + error);
  });

// 2. Initializes the application after connecting by opening a model.
function initApp(domain) {
  const modelService = domain.models();
  modelService.openAutoCreate({
    collection: "example",
    id: "getting-started",
    data: { text: "Hello World" }
  })
  .then(initModel)
  .catch((error) => {
    console.log("Could not open model: " + error);
  });
}

// 3. Initializes the model once the model is open.
function initModel(model) {
  const stringModel = model.elementAt("text");
  const textArea = document.getElementById("textarea");

  // Sets the value of the text area and performs a two-way-binding.
  ConvergenceInputElementBinder.bindTextInput(textArea, stringModel);
}
```

And yes, DOMAIN_URL is the right string, it is not empty.

**Comment by mmacfadden** [comment]
Hello! Thanks for reporting this issue. I will try to replicate it locally. In general, we use chrome for development, so chrome is what we test with most. It's possible that a recent update has caused some issue.

**Comment by Rubix982** [comment]
Hi, @mmacfadden! Thank you for the reply! If there's anything I can help with, do let me know please.

**Comment by Rubix982** [comment]
Closing this. I just setup a fresh, clean install of Chrome on a fresh Linux installation, and `convergence` works as expected. Probably configuration of Chrome on my end or extensions causing weird issues. Thank you!

**Comment by mmacfadden** [comment]
No problem. If you have any other issues.. let us know!
